{{- $templateData := dict "operationMode" "aod-worker" "replicaCount" .Values.dataPipeline.aodWorker.replicaCount "environment" .Values.dataPipeline.aodWorker.environment }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}
