{{- $templateData := dict "operationMode" "incr-repo-worker" }}
{{- $_ := set $templateData "replicaCount" .Values.dataPipeline.incrementalRepoWorker.replicaCount }}
{{- $_ := set $templateData "environment" .Values.dataPipeline.incrementalRepoWorker.environment }}
{{- $_ := set $templateData "javaOptions" .Values.dataPipeline.incrementalRepoWorker.javaOptions }}
{{- $_ := set $templateData "processorThreadCount" .Values.dataPipeline.incrementalRepoWorker.processorThreadCount }}
{{- $_ := set $templateData "maxConcurrentJobs" .Values.dataPipeline.incrementalRepoWorker.maxConcurrentJobs }}
{{- $_ := set $templateData "cpuLimits" .Values.dataPipeline.incrementalRepoWorker.limits.cpu }}
{{- $_ := set $templateData "memoryLimits" .Values.dataPipeline.incrementalRepoWorker.limits.memory }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}
