{{- $templateVars := dict "operationMode" "new-repo-worker" "replicaCount" .Values.dataPipeline.deploy.newRepoWorker.replicaCount }}
{{- $templateData := dict "Values" .Values "templateVars" $templateVars }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}
