{{- $templateData := dict "operationMode" "new-repo-worker" "replicaCount" .Values.dataPipeline.newRepoWorker.replicaCount "environment" .Values.dataPipeline.newRepoWorker.environment }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}
