{{- $templateData := dict "operationMode" "aod-worker" }}
{{- $_ := set $templateData "operationMode" "utility" }}
{{- $_ := set $templateData "replicaCount" 1 }}
{{- $_ := set $templateData "requeueAOD" "false" }}
{{- $_ := set $templateData "logLevel" "DEBUG" }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}

