# We'll start with values for the environment we'll be living in
environment:
  parentName: sandbox
  modifierValue: ""

dataPipeline:
  build:
    commitSHA: ""

  environment:
    - name: GP_AOD_QUEUE_NAME
      value: "java-aod-repo-process-request"
    - name: GP_REQUEUE_AOD
      value: true

  newRepoWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    environment:
      - name: GP_REPO_PROCESSING_QUEUE_NAME
        value: "java-new-repo-process-request"
      - name: GP_COMMIT_PROCESSOR_THREADS
        value: 2
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700

  incrementalRepoWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    environment:
      - name: GP_REPO_PROCESSING_QUEUE_NAME
        value: "java-incremental-repo-process-request"
      - name: GP_COMMIT_PROCESSOR_THREADS
        value: 2
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700

  aodWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    environment:
      - name: GP_REPO_PROCESSING_QUEUE_NAME
        value: "java-aod-repo-process-request"
      - name: GP_COMMIT_PROCESSOR_THREADS
        value: 2
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
