# We'll start with values for the environment we'll be living in
environment:
  parentName: sandbox
  modifierValue: ""

dataPipeline:
  build:
    commitSHA: ""

  environment:
    - name: GP_AOD_QUEUE_NAME
      value: "java-aod-repo-process-request"
    - name: GP_REQUEUE_AOD
      value: true

  newRepoWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    maxConcurrentJobs: 1
    processorThreadCount: 2
    environment:
      - name: GP_REPO_PROCESSING_QUEUE_NAME
        value: "java-new-repo-process-request"
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
    limits:
      cpu: "4"
      memory: 8Gi

  incrementalRepoWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    maxConcurrentJobs: 1
    processorThreadCount: 2
    environment:
      - name: GP_REPO_PROCESSING_QUEUE_NAME
        value: "java-incremental-repo-process-request"
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
    limits:
      cpu: "4"
      memory: 8Gi

  aodWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    maxConcurrentJobs: 1
    processorThreadCount: 2
    environment:
      - name: GP_REPO_PROCESSING_QUEUE_NAME
        value: "java-aod-repo-process-request"
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
    limits:
      cpu: "4"
      memory: 8Gi
